# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Macmode < Formula
  desc ""
  homepage "https://github.com/lkyuchukov/macmode"
  version "0.1.4"
  depends_on :macos

  on_macos do
    url "https://github.com/lkyuchukov/macmode/releases/download/v0.1.4/macmode_0.1.4_darwin_all.tar.gz"
    sha256 "02e47e72114116a77017be9b315195227f8dd2af295b7910b37c29e8a2bf2d53"

    def install
      bin.install "macmode"
    end
  end
end
